name: mini
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  video_player: ^2.8.1
  
  firebase_storage: ^11.5.2
  # location: ^5.0.3
  csv: ^5.1.1
  firebase_database: ^10.3.5
  # latlong2: ^0.9.0
  # flutter_map: ^6.0.1
  # flutter_map: ^0.15.0
  # latlong2: ^0.9.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.2
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^7.6.2
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  firebase_core: ^2.13.0
  
  

  
  firebase_auth: ^4.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/bike.jpeg
    - assets/images/road.jpeg
    - assets/images/sign.gif
    - assets/images/log.jpeg
    - assets/images/dest.jpg